/*
 Infomaniak Design System - iOS
 Copyright (C) 2026 Infomaniak Network SA

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Do not edit directly, this file was auto-generated.
 */

import SwiftUI
import ESDSFoundation
import ESDSPrimitives

extension ESDSTheme.Color {
    static let contacts = ESDSTheme.Color(
        backgroundBrandCalendarDefault: SwiftUI.Color(light: PrimitiveToken.Color.aqua400, dark: PrimitiveToken.Color.aqua300),
        backgroundBrandCalendarHover: SwiftUI.Color(light: PrimitiveToken.Color.aqua500, dark: PrimitiveToken.Color.aqua200),
        backgroundBrandCalendarPressed: SwiftUI.Color(light: PrimitiveToken.Color.aqua600, dark: PrimitiveToken.Color.aqua400),
        backgroundBrandContactsDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet300, dark: PrimitiveToken.Color.violet300),
        backgroundBrandContactsHover: SwiftUI.Color(light: PrimitiveToken.Color.violet400, dark: PrimitiveToken.Color.violet200),
        backgroundBrandContactsPressed: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet400),
        backgroundBrandDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet300, dark: PrimitiveToken.Color.violet300),
        backgroundBrandEuriaDefault: SwiftUI.Color(light: PrimitiveToken.Color.ocean700, dark: PrimitiveToken.Color.ocean400),
        backgroundBrandEuriaHover: SwiftUI.Color(light: PrimitiveToken.Color.ocean800, dark: PrimitiveToken.Color.ocean300),
        backgroundBrandEuriaPressed: SwiftUI.Color(light: PrimitiveToken.Color.ocean900, dark: PrimitiveToken.Color.ocean500),
        backgroundBrandHover: SwiftUI.Color(light: PrimitiveToken.Color.violet400, dark: PrimitiveToken.Color.violet200),
        backgroundBrandInfomaniakDefault: SwiftUI.Color(light: PrimitiveToken.Color.blue500, dark: PrimitiveToken.Color.blue400),
        backgroundBrandInfomaniakHover: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue300),
        backgroundBrandInfomaniakPressed: SwiftUI.Color(light: PrimitiveToken.Color.blue700, dark: PrimitiveToken.Color.blue500),
        backgroundBrandKchatDefault: SwiftUI.Color(light: PrimitiveToken.Color.cyan400, dark: PrimitiveToken.Color.cyan300),
        backgroundBrandKchatHover: SwiftUI.Color(light: PrimitiveToken.Color.cyan500, dark: PrimitiveToken.Color.cyan200),
        backgroundBrandKchatPressed: SwiftUI.Color(light: PrimitiveToken.Color.cyan600, dark: PrimitiveToken.Color.cyan400),
        backgroundBrandKdriveDefault: SwiftUI.Color(light: PrimitiveToken.Color.indigo400, dark: PrimitiveToken.Color.indigo300),
        backgroundBrandKdriveHover: SwiftUI.Color(light: PrimitiveToken.Color.indigo500, dark: PrimitiveToken.Color.indigo200),
        backgroundBrandKdrivePressed: SwiftUI.Color(light: PrimitiveToken.Color.indigo600, dark: PrimitiveToken.Color.indigo400),
        backgroundBrandKnoteDefault: SwiftUI.Color(light: PrimitiveToken.Color.coral500, dark: PrimitiveToken.Color.coral300),
        backgroundBrandKnoteHover: SwiftUI.Color(light: PrimitiveToken.Color.coral600, dark: PrimitiveToken.Color.coral200),
        backgroundBrandKnotePressed: SwiftUI.Color(light: PrimitiveToken.Color.coral700, dark: PrimitiveToken.Color.coral400),
        backgroundBrandMailDefault: SwiftUI.Color(light: PrimitiveToken.Color.pink500, dark: PrimitiveToken.Color.pink300),
        backgroundBrandMailHover: SwiftUI.Color(light: PrimitiveToken.Color.pink600, dark: PrimitiveToken.Color.pink200),
        backgroundBrandMailPressed: SwiftUI.Color(light: PrimitiveToken.Color.pink700, dark: PrimitiveToken.Color.pink400),
        backgroundBrandPressed: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet400),
        backgroundBrandSecurityDefault: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple300),
        backgroundBrandSecurityHover: SwiftUI.Color(light: PrimitiveToken.Color.purple700, dark: PrimitiveToken.Color.purple200),
        backgroundBrandSecurityPressed: SwiftUI.Color(light: PrimitiveToken.Color.purple800, dark: PrimitiveToken.Color.purple400),
        backgroundBrandSwisstransferDefault: SwiftUI.Color(light: PrimitiveToken.Color.emerald500, dark: PrimitiveToken.Color.emerald300),
        backgroundBrandSwisstransferHover: SwiftUI.Color(light: PrimitiveToken.Color.emerald600, dark: PrimitiveToken.Color.emerald200),
        backgroundBrandSwisstransferPressed: SwiftUI.Color(light: PrimitiveToken.Color.emerald700, dark: PrimitiveToken.Color.emerald400),
        backgroundDisabled: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray800),
        backgroundElevationOverlayDefault: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray800),
        backgroundElevationOverlayHover: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray700),
        backgroundElevationOverlayPressed: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray900),
        backgroundElevationOverlaySelected: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray900),
        backgroundElevationRaisedDefault: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.gray800),
        backgroundElevationRaisedHover: SwiftUI.Color(light: PrimitiveToken.Color.gray50, dark: PrimitiveToken.Color.gray700),
        backgroundElevationRaisedPressed: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray900),
        backgroundElevationRaisedSelected: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray900),
        backgroundElevationSunkenDefault: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray950),
        backgroundElevationSunkenHover: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray900),
        backgroundElevationSunkenPressed: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray800),
        backgroundElevationSunkenSelected: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray800),
        backgroundElevationSurfaceDefault: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.gray800),
        backgroundElevationSurfaceHover: SwiftUI.Color(light: PrimitiveToken.Color.gray50, dark: PrimitiveToken.Color.gray700),
        backgroundElevationSurfacePressed: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray900),
        backgroundElevationSurfaceSelected: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray900),
        backgroundFeedbackErrorDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.red400, dark: PrimitiveToken.Color.red400),
        backgroundFeedbackErrorDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.red500, dark: PrimitiveToken.Color.red300),
        backgroundFeedbackErrorDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.red600, dark: PrimitiveToken.Color.red500),
        backgroundFeedbackErrorDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.red200, dark: PrimitiveToken.Color.red900),
        backgroundFeedbackErrorDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.red300, dark: PrimitiveToken.Color.red800),
        backgroundFeedbackErrorDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.red400, dark: PrimitiveToken.Color.red950),
        backgroundFeedbackSuccessDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.lime500, dark: PrimitiveToken.Color.lime400),
        backgroundFeedbackSuccessDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.lime600, dark: PrimitiveToken.Color.lime300),
        backgroundFeedbackSuccessDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.lime700, dark: PrimitiveToken.Color.lime500),
        backgroundFeedbackSuccessDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.lime200, dark: PrimitiveToken.Color.lime900),
        backgroundFeedbackSuccessDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.lime300, dark: PrimitiveToken.Color.lime800),
        backgroundFeedbackSuccessDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.lime400, dark: PrimitiveToken.Color.lime950),
        backgroundFeedbackWarningDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.orange400, dark: PrimitiveToken.Color.orange300),
        backgroundFeedbackWarningDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.orange500, dark: PrimitiveToken.Color.orange200),
        backgroundFeedbackWarningDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.orange600, dark: PrimitiveToken.Color.orange400),
        backgroundFeedbackWarningDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.orange200, dark: PrimitiveToken.Color.orange900),
        backgroundFeedbackWarningDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.orange300, dark: PrimitiveToken.Color.orange800),
        backgroundFeedbackWarningDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.orange400, dark: PrimitiveToken.Color.orange950),
        borderBrandCalendarDefault: SwiftUI.Color(light: PrimitiveToken.Color.aqua400, dark: PrimitiveToken.Color.aqua300),
        borderBrandCalendarHover: SwiftUI.Color(light: PrimitiveToken.Color.aqua500, dark: PrimitiveToken.Color.aqua200),
        borderBrandCalendarPressed: SwiftUI.Color(light: PrimitiveToken.Color.aqua600, dark: PrimitiveToken.Color.aqua400),
        borderBrandContactsDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet300, dark: PrimitiveToken.Color.violet300),
        borderBrandContactsHover: SwiftUI.Color(light: PrimitiveToken.Color.violet400, dark: PrimitiveToken.Color.violet200),
        borderBrandContactsPressed: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet400),
        borderBrandDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet300, dark: PrimitiveToken.Color.violet300),
        borderBrandEuriaDefault: SwiftUI.Color(light: PrimitiveToken.Color.ocean600, dark: PrimitiveToken.Color.ocean400),
        borderBrandEuriaHover: SwiftUI.Color(light: PrimitiveToken.Color.ocean700, dark: PrimitiveToken.Color.ocean300),
        borderBrandEuriaPressed: SwiftUI.Color(light: PrimitiveToken.Color.ocean800, dark: PrimitiveToken.Color.ocean500),
        borderBrandHover: SwiftUI.Color(light: PrimitiveToken.Color.violet400, dark: PrimitiveToken.Color.violet200),
        borderBrandInfomaniakDefault: SwiftUI.Color(light: PrimitiveToken.Color.blue500, dark: PrimitiveToken.Color.blue400),
        borderBrandInfomaniakHover: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue300),
        borderBrandInfomaniakPressed: SwiftUI.Color(light: PrimitiveToken.Color.blue700, dark: PrimitiveToken.Color.blue500),
        borderBrandKchatDefault: SwiftUI.Color(light: PrimitiveToken.Color.cyan400, dark: PrimitiveToken.Color.cyan300),
        borderBrandKchatHover: SwiftUI.Color(light: PrimitiveToken.Color.cyan500, dark: PrimitiveToken.Color.cyan200),
        borderBrandKchatPressed: SwiftUI.Color(light: PrimitiveToken.Color.cyan600, dark: PrimitiveToken.Color.cyan400),
        borderBrandKdriveDefault: SwiftUI.Color(light: PrimitiveToken.Color.indigo400, dark: PrimitiveToken.Color.indigo300),
        borderBrandKdriveHover: SwiftUI.Color(light: PrimitiveToken.Color.indigo500, dark: PrimitiveToken.Color.indigo200),
        borderBrandKdrivePressed: SwiftUI.Color(light: PrimitiveToken.Color.indigo600, dark: PrimitiveToken.Color.indigo400),
        borderBrandKnoteDefault: SwiftUI.Color(light: PrimitiveToken.Color.coral400, dark: PrimitiveToken.Color.coral300),
        borderBrandKnoteHover: SwiftUI.Color(light: PrimitiveToken.Color.coral500, dark: PrimitiveToken.Color.coral200),
        borderBrandKnotePressed: SwiftUI.Color(light: PrimitiveToken.Color.coral600, dark: PrimitiveToken.Color.coral400),
        borderBrandMailDefault: SwiftUI.Color(light: PrimitiveToken.Color.pink500, dark: PrimitiveToken.Color.pink300),
        borderBrandMailHover: SwiftUI.Color(light: PrimitiveToken.Color.pink600, dark: PrimitiveToken.Color.pink200),
        borderBrandMailPressed: SwiftUI.Color(light: PrimitiveToken.Color.pink700, dark: PrimitiveToken.Color.pink400),
        borderBrandPressed: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet400),
        borderBrandSecurityDefault: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple300),
        borderBrandSecurityHover: SwiftUI.Color(light: PrimitiveToken.Color.purple700, dark: PrimitiveToken.Color.purple200),
        borderBrandSecurityPressed: SwiftUI.Color(light: PrimitiveToken.Color.purple800, dark: PrimitiveToken.Color.purple400),
        borderBrandSwisstransferDefault: SwiftUI.Color(light: PrimitiveToken.Color.emerald500, dark: PrimitiveToken.Color.emerald300),
        borderBrandSwisstransferHover: SwiftUI.Color(light: PrimitiveToken.Color.emerald600, dark: PrimitiveToken.Color.emerald200),
        borderBrandSwisstransferPressed: SwiftUI.Color(light: PrimitiveToken.Color.emerald700, dark: PrimitiveToken.Color.emerald400),
        borderDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        borderDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.gray500, dark: PrimitiveToken.Color.gray400),
        borderDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.gray600, dark: PrimitiveToken.Color.gray600),
        borderDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray600),
        borderDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        borderDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.gray500, dark: PrimitiveToken.Color.gray700),
        borderDim3Default: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray700),
        borderDim3Hover: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray600),
        borderDim3Pressed: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray900),
        borderDim4Default: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray800),
        borderDim4Hover: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray700),
        borderDim4Pressed: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray900),
        borderFeedbackErrorDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.red600, dark: PrimitiveToken.Color.red400),
        borderFeedbackErrorDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.red700, dark: PrimitiveToken.Color.red300),
        borderFeedbackErrorDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.red800, dark: PrimitiveToken.Color.red500),
        borderFeedbackErrorDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.red200, dark: PrimitiveToken.Color.red700),
        borderFeedbackErrorDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.red300, dark: PrimitiveToken.Color.red600),
        borderFeedbackErrorDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.red400, dark: PrimitiveToken.Color.red900),
        borderFeedbackSuccessDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.lime600, dark: PrimitiveToken.Color.lime400),
        borderFeedbackSuccessDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.lime700, dark: PrimitiveToken.Color.lime300),
        borderFeedbackSuccessDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.lime800, dark: PrimitiveToken.Color.lime500),
        borderFeedbackSuccessDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.lime200, dark: PrimitiveToken.Color.lime700),
        borderFeedbackSuccessDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.lime300, dark: PrimitiveToken.Color.lime600),
        borderFeedbackSuccessDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.lime400, dark: PrimitiveToken.Color.lime900),
        borderFeedbackWarningDim1Default: SwiftUI.Color(light: PrimitiveToken.Color.orange600, dark: PrimitiveToken.Color.orange400),
        borderFeedbackWarningDim1Hover: SwiftUI.Color(light: PrimitiveToken.Color.orange700, dark: PrimitiveToken.Color.orange300),
        borderFeedbackWarningDim1Pressed: SwiftUI.Color(light: PrimitiveToken.Color.orange800, dark: PrimitiveToken.Color.orange500),
        borderFeedbackWarningDim2Default: SwiftUI.Color(light: PrimitiveToken.Color.orange200, dark: PrimitiveToken.Color.orange700),
        borderFeedbackWarningDim2Hover: SwiftUI.Color(light: PrimitiveToken.Color.orange300, dark: PrimitiveToken.Color.orange600),
        borderFeedbackWarningDim2Pressed: SwiftUI.Color(light: PrimitiveToken.Color.orange400, dark: PrimitiveToken.Color.orange900),
        contentBrandCalendarDefault: SwiftUI.Color(light: PrimitiveToken.Color.aqua500, dark: PrimitiveToken.Color.aqua400),
        contentBrandCalendarHover: SwiftUI.Color(light: PrimitiveToken.Color.aqua600, dark: PrimitiveToken.Color.aqua300),
        contentBrandCalendarPressed: SwiftUI.Color(light: PrimitiveToken.Color.aqua700, dark: PrimitiveToken.Color.aqua500),
        contentBrandContactsDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet300),
        contentBrandContactsHover: SwiftUI.Color(light: PrimitiveToken.Color.violet600, dark: PrimitiveToken.Color.violet200),
        contentBrandContactsPressed: SwiftUI.Color(light: PrimitiveToken.Color.violet700, dark: PrimitiveToken.Color.violet400),
        contentBrandDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet300),
        contentBrandEuriaDefault: SwiftUI.Color(light: PrimitiveToken.Color.ocean600, dark: PrimitiveToken.Color.ocean400),
        contentBrandEuriaHover: SwiftUI.Color(light: PrimitiveToken.Color.ocean700, dark: PrimitiveToken.Color.ocean300),
        contentBrandEuriaPressed: SwiftUI.Color(light: PrimitiveToken.Color.ocean800, dark: PrimitiveToken.Color.ocean500),
        contentBrandHover: SwiftUI.Color(light: PrimitiveToken.Color.violet600, dark: PrimitiveToken.Color.violet200),
        contentBrandInfomaniakDefault: SwiftUI.Color(light: PrimitiveToken.Color.blue700, dark: PrimitiveToken.Color.blue400),
        contentBrandInfomaniakHover: SwiftUI.Color(light: PrimitiveToken.Color.blue800, dark: PrimitiveToken.Color.blue300),
        contentBrandInfomaniakPressed: SwiftUI.Color(light: PrimitiveToken.Color.blue900, dark: PrimitiveToken.Color.blue500),
        contentBrandKchatDefault: SwiftUI.Color(light: PrimitiveToken.Color.cyan600, dark: PrimitiveToken.Color.cyan400),
        contentBrandKchatHover: SwiftUI.Color(light: PrimitiveToken.Color.cyan700, dark: PrimitiveToken.Color.cyan300),
        contentBrandKchatPressed: SwiftUI.Color(light: PrimitiveToken.Color.cyan800, dark: PrimitiveToken.Color.cyan500),
        contentBrandKdriveDefault: SwiftUI.Color(light: PrimitiveToken.Color.indigo500, dark: PrimitiveToken.Color.indigo300),
        contentBrandKdriveHover: SwiftUI.Color(light: PrimitiveToken.Color.indigo600, dark: PrimitiveToken.Color.indigo200),
        contentBrandKdrivePressed: SwiftUI.Color(light: PrimitiveToken.Color.indigo700, dark: PrimitiveToken.Color.indigo400),
        contentBrandKnoteDefault: SwiftUI.Color(light: PrimitiveToken.Color.coral600, dark: PrimitiveToken.Color.coral400),
        contentBrandKnoteHover: SwiftUI.Color(light: PrimitiveToken.Color.coral700, dark: PrimitiveToken.Color.coral300),
        contentBrandKnotePressed: SwiftUI.Color(light: PrimitiveToken.Color.coral800, dark: PrimitiveToken.Color.coral500),
        contentBrandMailDefault: SwiftUI.Color(light: PrimitiveToken.Color.pink700, dark: PrimitiveToken.Color.pink400),
        contentBrandMailHover: SwiftUI.Color(light: PrimitiveToken.Color.pink800, dark: PrimitiveToken.Color.pink300),
        contentBrandMailPressed: SwiftUI.Color(light: PrimitiveToken.Color.pink900, dark: PrimitiveToken.Color.pink500),
        contentBrandPressed: SwiftUI.Color(light: PrimitiveToken.Color.violet700, dark: PrimitiveToken.Color.violet400),
        contentBrandSecurityDefault: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple400),
        contentBrandSecurityHover: SwiftUI.Color(light: PrimitiveToken.Color.purple700, dark: PrimitiveToken.Color.purple300),
        contentBrandSecurityPressed: SwiftUI.Color(light: PrimitiveToken.Color.purple800, dark: PrimitiveToken.Color.purple500),
        contentBrandSwisstransferDefault: SwiftUI.Color(light: PrimitiveToken.Color.emerald600, dark: PrimitiveToken.Color.emerald400),
        contentBrandSwisstransferHover: SwiftUI.Color(light: PrimitiveToken.Color.emerald700, dark: PrimitiveToken.Color.emerald300),
        contentBrandSwisstransferPressed: SwiftUI.Color(light: PrimitiveToken.Color.emerald800, dark: PrimitiveToken.Color.emerald500),
        contentDisabled: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        contentFeedbackErrorDefault: SwiftUI.Color(light: PrimitiveToken.Color.red700, dark: PrimitiveToken.Color.red300),
        contentFeedbackErrorHover: SwiftUI.Color(light: PrimitiveToken.Color.red800, dark: PrimitiveToken.Color.red200),
        contentFeedbackErrorPressed: SwiftUI.Color(light: PrimitiveToken.Color.red900, dark: PrimitiveToken.Color.red400),
        contentFeedbackSuccessDefault: SwiftUI.Color(light: PrimitiveToken.Color.lime700, dark: PrimitiveToken.Color.lime300),
        contentFeedbackSuccessHover: SwiftUI.Color(light: PrimitiveToken.Color.lime800, dark: PrimitiveToken.Color.lime200),
        contentFeedbackSuccessPressed: SwiftUI.Color(light: PrimitiveToken.Color.lime900, dark: PrimitiveToken.Color.lime400),
        contentFeedbackWarningDefault: SwiftUI.Color(light: PrimitiveToken.Color.orange700, dark: PrimitiveToken.Color.orange300),
        contentFeedbackWarningHover: SwiftUI.Color(light: PrimitiveToken.Color.orange800, dark: PrimitiveToken.Color.orange200),
        contentFeedbackWarningPressed: SwiftUI.Color(light: PrimitiveToken.Color.orange900, dark: PrimitiveToken.Color.orange400),
        contentInverse: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray800),
        contentOnBrandCalendarDefault: SwiftUI.Color(light: PrimitiveToken.Color.aqua950, dark: PrimitiveToken.Color.aqua950),
        contentOnBrandContactsDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet950, dark: PrimitiveToken.Color.violet950),
        contentOnBrandDefault: SwiftUI.Color(light: PrimitiveToken.Color.violet950, dark: PrimitiveToken.Color.violet950),
        contentOnBrandEuriaDefault: SwiftUI.Color(light: PrimitiveToken.Color.ocean50, dark: PrimitiveToken.Color.ocean950),
        contentOnBrandInfomaniakDefault: SwiftUI.Color(light: PrimitiveToken.Color.blue950, dark: PrimitiveToken.Color.blue950),
        contentOnBrandKchatDefault: SwiftUI.Color(light: PrimitiveToken.Color.cyan950, dark: PrimitiveToken.Color.cyan950),
        contentOnBrandKdriveDefault: SwiftUI.Color(light: PrimitiveToken.Color.indigo50, dark: PrimitiveToken.Color.indigo950),
        contentOnBrandKnoteDefault: SwiftUI.Color(light: PrimitiveToken.Color.coral50, dark: PrimitiveToken.Color.coral950),
        contentOnBrandMailDefault: SwiftUI.Color(light: PrimitiveToken.Color.pink50, dark: PrimitiveToken.Color.pink950),
        contentOnBrandSecurityDefault: SwiftUI.Color(light: PrimitiveToken.Color.purple50, dark: PrimitiveToken.Color.purple950),
        contentOnBrandSwisstransferDefault: SwiftUI.Color(light: PrimitiveToken.Color.emerald950, dark: PrimitiveToken.Color.emerald950),
        contentOnDisabled: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        contentOnFeedbackErrorDim1: SwiftUI.Color(light: PrimitiveToken.Color.red900, dark: PrimitiveToken.Color.red100),
        contentOnFeedbackErrorDim2: SwiftUI.Color(light: PrimitiveToken.Color.red950, dark: PrimitiveToken.Color.red950),
        contentOnFeedbackSuccessDim1: SwiftUI.Color(light: PrimitiveToken.Color.lime950, dark: PrimitiveToken.Color.lime50),
        contentOnFeedbackSuccessDim2: SwiftUI.Color(light: PrimitiveToken.Color.lime950, dark: PrimitiveToken.Color.lime950),
        contentOnFeedbackWarningDim1: SwiftUI.Color(light: PrimitiveToken.Color.orange900, dark: PrimitiveToken.Color.orange50),
        contentOnFeedbackWarningDim2: SwiftUI.Color(light: PrimitiveToken.Color.orange950, dark: PrimitiveToken.Color.orange950),
        contentPrimary: SwiftUI.Color(light: PrimitiveToken.Color.gray800, dark: PrimitiveToken.Color.gray100),
        contentSecondary: SwiftUI.Color(light: PrimitiveToken.Color.gray600, dark: PrimitiveToken.Color.gray300),
        contentTertiary: SwiftUI.Color(light: PrimitiveToken.Color.gray500, dark: PrimitiveToken.Color.gray400),
        shadow2xl: SwiftUI.Color(light: PrimitiveToken.Color.gray40014, dark: PrimitiveToken.Color.gray95014),
        shadowLg: SwiftUI.Color(light: PrimitiveToken.Color.gray40010, dark: PrimitiveToken.Color.gray95010),
        shadowMd: SwiftUI.Color(light: PrimitiveToken.Color.gray4008, dark: PrimitiveToken.Color.gray9508),
        shadowSm: SwiftUI.Color(light: PrimitiveToken.Color.gray4006, dark: PrimitiveToken.Color.gray9506),
        shadowXl: SwiftUI.Color(light: PrimitiveToken.Color.gray40010, dark: PrimitiveToken.Color.gray95010),
        shadowXs: SwiftUI.Color(light: PrimitiveToken.Color.transparent, dark: PrimitiveToken.Color.transparent)
    )
}