/*
 Infomaniak Design System - iOS
 Copyright (C) 2026 Infomaniak Network SA

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Do not edit directly, this file was auto-generated.
 */

import SwiftUI

#if canImport(UIKit)
import UIKit
#endif

public enum ESDSSymbols: Sendable {
    public struct Symbol: Sendable {
        private let name: String
    
        public var image: SwiftUI.Image {
            SwiftUI.Image(name, bundle: .module)
        }
    
        #if canImport(UIKit)
        public var uiImage: UIKit.UIImage {
            guard let image = UIKit.UIImage(named: name, in: .module, compatibleWith: nil) else {
                preconditionFailure("Missing symbol asset \"\(name)\".")
            }
            return image
        }
        #endif
    
        fileprivate init(name: String) {
            self.name = name
        }
    }

    public static let aLargeSmall = Symbol(name: "a-large-small")
    public static let alarmClock = Symbol(name: "alarm-clock")
    public static let arrowDown = Symbol(name: "arrow-down")
    public static let arrowLeft = Symbol(name: "arrow-left")
    public static let arrowRight = Symbol(name: "arrow-right")
    public static let arrowTurnUpLeft = Symbol(name: "arrow-turn-up-left")
    public static let arrowTurnUpRight = Symbol(name: "arrow-turn-up-right")
    public static let arrowUpRight = Symbol(name: "arrow-up-right")
    public static let arrowUp = Symbol(name: "arrow-up")
    public static let arrowsCrossOut = Symbol(name: "arrows-cross-out")
    public static let arrowsFourDiagonalIn = Symbol(name: "arrows-four-diagonal-in")
    public static let arrowsFourDiagonalOut = Symbol(name: "arrows-four-diagonal-out")
    public static let arrowsTurnUpLeft = Symbol(name: "arrows-turn-up-left")
    public static let arrowsTwoDiagonalIn = Symbol(name: "arrows-two-diagonal-in")
    public static let arrowsUpDown = Symbol(name: "arrows-up-down")
    public static let atSign = Symbol(name: "at-sign")
    public static let bellSlash = Symbol(name: "bell-slash")
    public static let bell = Symbol(name: "bell")
    public static let bold = Symbol(name: "bold")
    public static let bookUser = Symbol(name: "book-user")
    public static let book = Symbol(name: "book")
    public static let bookmarkSlash = Symbol(name: "bookmark-slash")
    public static let bookmark = Symbol(name: "bookmark")
    public static let boxLid = Symbol(name: "box-lid")
    public static let briefcase = Symbol(name: "briefcase")
    public static let broom = Symbol(name: "broom")
    public static let bubbleLeftText = Symbol(name: "bubble-left-text")
    public static let bubbleTopRightCircle = Symbol(name: "bubble-top-right-circle")
    public static let bucketDrop = Symbol(name: "bucket-drop")
    public static let bug = Symbol(name: "bug")
    public static let building = Symbol(name: "building")
    public static let cakeCandles = Symbol(name: "cake-candles")
    public static let calendarCheck = Symbol(name: "calendar-check")
    public static let calendarCross = Symbol(name: "calendar-cross")
    public static let calendarDots = Symbol(name: "calendar-dots")
    public static let calendarNumberOne = Symbol(name: "calendar-number-one")
    public static let calendarPlus = Symbol(name: "calendar-plus")
    public static let calendarUser = Symbol(name: "calendar-user")
    public static let calendar = Symbol(name: "calendar")
    public static let cardUser = Symbol(name: "card-user")
    public static let check = Symbol(name: "check")
    public static let checkmarkList = Symbol(name: "checkmark-list")
    public static let chevronDown = Symbol(name: "chevron-down")
    public static let chevronLeftSlashChevronRight = Symbol(name: "chevron-left-slash-chevron-right")
    public static let chevronLeft = Symbol(name: "chevron-left")
    public static let chevronRight = Symbol(name: "chevron-right")
    public static let chevronUp = Symbol(name: "chevron-up")
    public static let chevronsLeftRight = Symbol(name: "chevrons-left-right")
    public static let chevronsUpDown = Symbol(name: "chevrons-up-down")
    public static let circleArrowAnticlockwise = Symbol(name: "circle-arrow-anticlockwise")
    public static let circleArrowClockwise = Symbol(name: "circle-arrow-clockwise")
    public static let circleArrowLeft = Symbol(name: "circle-arrow-left")
    public static let circleArrowRight = Symbol(name: "circle-arrow-right")
    public static let circleArrowsAnticlockwise = Symbol(name: "circle-arrows-anticlockwise")
    public static let circleCheckFilled = Symbol(name: "circle-check-filled")
    public static let circleCheck = Symbol(name: "circle-check")
    public static let circleCrossFilled = Symbol(name: "circle-cross-filled")
    public static let circleCross = Symbol(name: "circle-cross")
    public static let circleEllipsis = Symbol(name: "circle-ellipsis")
    public static let circleFadingArrowUp = Symbol(name: "circle-fading-arrow-up")
    public static let circleInfoFilled = Symbol(name: "circle-info-filled")
    public static let circleInfo = Symbol(name: "circle-info")
    public static let circleLineCircle = Symbol(name: "circle-line-circle")
    public static let circleOpenTopRight = Symbol(name: "circle-open-top-right")
    public static let circlePlus = Symbol(name: "circle-plus")
    public static let circleQuestionFilled = Symbol(name: "circle-question-filled")
    public static let circleQuestion = Symbol(name: "circle-question")
    public static let circleUser = Symbol(name: "circle-user")
    public static let circle = Symbol(name: "circle")
    public static let circularArrowsClockwise = Symbol(name: "circular-arrows-clockwise")
    public static let clipboardArrowLeft = Symbol(name: "clipboard-arrow-left")
    public static let clock = Symbol(name: "clock")
    public static let cloudArrowAnticlockwise = Symbol(name: "cloud-arrow-anticlockwise")
    public static let cloudArrowDown = Symbol(name: "cloud-arrow-down")
    public static let cloudArrowUp = Symbol(name: "cloud-arrow-up")
    public static let cloudCheck = Symbol(name: "cloud-check")
    public static let cloudExclamationMark = Symbol(name: "cloud-exclamation-mark")
    public static let cloudSlash = Symbol(name: "cloud-slash")
    public static let cloud = Symbol(name: "cloud")
    public static let cog = Symbol(name: "cog")
    public static let columnsFour = Symbol(name: "columns-four")
    public static let columnsThree = Symbol(name: "columns-three")
    public static let concentricCircles = Symbol(name: "concentric-circles")
    public static let cornerBrackets = Symbol(name: "corner-brackets")
    public static let cross = Symbol(name: "cross")
    public static let crown = Symbol(name: "crown")
    public static let diamondsStackedVertical = Symbol(name: "diamonds-stacked-vertical")
    public static let doorOpen = Symbol(name: "door-open")
    public static let dotsList = Symbol(name: "dots-list")
    public static let dotsNine = Symbol(name: "dots-nine")
    public static let dotsSix = Symbol(name: "dots-six")
    public static let dotsThreeHorizontal = Symbol(name: "dots-three-horizontal")
    public static let dotsThreeVertical = Symbol(name: "dots-three-vertical")
    public static let doubleQuotesClosing = Symbol(name: "double-quotes-closing")
    public static let envelopeCross = Symbol(name: "envelope-cross")
    public static let envelopeExclamationMark = Symbol(name: "envelope-exclamation-mark")
    public static let envelopeFilled = Symbol(name: "envelope-filled")
    public static let envelopeMagnifyingGlass = Symbol(name: "envelope-magnifying-glass")
    public static let envelopeMinus = Symbol(name: "envelope-minus")
    public static let envelopeOpen = Symbol(name: "envelope-open")
    public static let envelopePlus = Symbol(name: "envelope-plus")
    public static let envelopeQuestionMark = Symbol(name: "envelope-question-mark")
    public static let envelope = Symbol(name: "envelope")
    public static let eyeClosed = Symbol(name: "eye-closed")
    public static let eyeSlash = Symbol(name: "eye-slash")
    public static let eye = Symbol(name: "eye")
    public static let fileBraces = Symbol(name: "file-braces")
    public static let fileBulletLines = Symbol(name: "file-bullet-lines")
    public static let fileChart = Symbol(name: "file-chart")
    public static let fileSunMountain = Symbol(name: "file-sun-mountain")
    public static let fileText = Symbol(name: "file-text")
    public static let fileZipper = Symbol(name: "file-zipper")
    public static let file = Symbol(name: "file")
    public static let flag = Symbol(name: "flag")
    public static let folderCross = Symbol(name: "folder-cross")
    public static let folderOpen = Symbol(name: "folder-open")
    public static let folderPlus = Symbol(name: "folder-plus")
    public static let folder = Symbol(name: "folder")
    public static let frameSunMountain = Symbol(name: "frame-sun-mountain")
    public static let funnel = Symbol(name: "funnel")
    public static let globe = Symbol(name: "globe")
    public static let gridThreeTwo = Symbol(name: "grid-three-two")
    public static let handshakeHeart = Symbol(name: "handshake-heart")
    public static let handshake = Symbol(name: "handshake")
    public static let hardDriveFilled = Symbol(name: "hard-drive-filled")
    public static let hardDrive = Symbol(name: "hard-drive")
    public static let hashSign = Symbol(name: "hash-sign")
    public static let heading1 = Symbol(name: "heading-1")
    public static let heading2 = Symbol(name: "heading-2")
    public static let heading3 = Symbol(name: "heading-3")
    public static let heading4 = Symbol(name: "heading-4")
    public static let headset = Symbol(name: "headset")
    public static let heart = Symbol(name: "heart")
    public static let highlighter = Symbol(name: "highlighter")
    public static let inbox = Symbol(name: "inbox")
    public static let isoCube = Symbol(name: "iso-cube")
    public static let italic = Symbol(name: "italic")
    public static let keyOptionApple = Symbol(name: "key-option-apple")
    public static let labelCross = Symbol(name: "label-cross")
    public static let languages = Symbol(name: "languages")
    public static let lightbulb = Symbol(name: "lightbulb")
    public static let linkBroken = Symbol(name: "link-broken")
    public static let linkHorizontal = Symbol(name: "link-horizontal")
    public static let link = Symbol(name: "link")
    public static let listFilter = Symbol(name: "list-filter")
    public static let listLeft = Symbol(name: "list-left")
    public static let listMagnifyingClass = Symbol(name: "list-magnifying-class")
    public static let list = Symbol(name: "list")
    public static let lockOpen = Symbol(name: "lock-open")
    public static let lock = Symbol(name: "lock")
    public static let loopedSquare = Symbol(name: "looped-square")
    public static let magnifyingGlassMinus = Symbol(name: "magnifying-glass-minus")
    public static let magnifyingGlassPlus = Symbol(name: "magnifying-glass-plus")
    public static let magnifyingGlass = Symbol(name: "magnifying-glass")
    public static let mapPin = Symbol(name: "map-pin")
    public static let mic = Symbol(name: "mic")
    public static let minus = Symbol(name: "minus")
    public static let monitor = Symbol(name: "monitor")
    public static let moon = Symbol(name: "moon")
    public static let mousePointerSparkle = Symbol(name: "mouse-pointer-sparkle")
    public static let mousePointer = Symbol(name: "mouse-pointer")
    public static let musicNote = Symbol(name: "music-note")
    public static let network = Symbol(name: "network")
    public static let numberList = Symbol(name: "number-list")
    public static let overlineRectangleUnderline = Symbol(name: "overline-rectangle-underline")
    public static let paperPlane = Symbol(name: "paper-plane")
    public static let paperclip = Symbol(name: "paperclip")
    public static let pen = Symbol(name: "pen")
    public static let pencilSparkles = Symbol(name: "pencil-sparkles")
    public static let pieSlice = Symbol(name: "pie-slice")
    public static let pin = Symbol(name: "pin")
    public static let plus = Symbol(name: "plus")
    public static let power = Symbol(name: "power")
    public static let productCalendarFilled = Symbol(name: "product-calendar-filled")
    public static let productCalendar = Symbol(name: "product-calendar")
    public static let productContactFilled = Symbol(name: "product-contact-filled")
    public static let productContact = Symbol(name: "product-contact")
    public static let productEuriaFilled = Symbol(name: "product-euria-filled")
    public static let productEuria = Symbol(name: "product-euria")
    public static let productKchatFilled = Symbol(name: "product-kchat-filled")
    public static let productKchat = Symbol(name: "product-kchat")
    public static let productKdriveFilled = Symbol(name: "product-kdrive-filled")
    public static let productKdrive = Symbol(name: "product-kdrive")
    public static let productKmeetFilled = Symbol(name: "product-kmeet-filled")
    public static let productKmeet = Symbol(name: "product-kmeet")
    public static let productMailFilled = Symbol(name: "product-mail-filled")
    public static let productMail = Symbol(name: "product-mail")
    public static let productSwisstransferFilled = Symbol(name: "product-swisstransfer-filled")
    public static let productSwisstransfer = Symbol(name: "product-swisstransfer")
    public static let rectangleDotsThree = Symbol(name: "rectangle-dots-three")
    public static let rectangleSquaresTwo = Symbol(name: "rectangle-squares-two")
    public static let rectangleTwo = Symbol(name: "rectangle-two")
    public static let rectangleUnderlineDashed = Symbol(name: "rectangle-underline-dashed")
    public static let rocket = Symbol(name: "rocket")
    public static let rowsFour = Symbol(name: "rows-four")
    public static let rowsThree = Symbol(name: "rows-three")
    public static let rowsTwo = Symbol(name: "rows-two")
    public static let scissors = Symbol(name: "scissors")
    public static let share = Symbol(name: "share")
    public static let shieldCheck = Symbol(name: "shield-check")
    public static let shieldExclamationMark = Symbol(name: "shield-exclamation-mark")
    public static let shieldQuestionMark = Symbol(name: "shield-question-mark")
    public static let shieldUser = Symbol(name: "shield-user")
    public static let shoppingCart = Symbol(name: "shopping-cart")
    public static let sidebarLeftChevronLeft = Symbol(name: "sidebar-left-chevron-left")
    public static let sidebarLeftChevronRight = Symbol(name: "sidebar-left-chevron-right")
    public static let sidebarLeft = Symbol(name: "sidebar-left")
    public static let slash = Symbol(name: "slash")
    public static let slidersHorizontal = Symbol(name: "sliders-horizontal")
    public static let slidersVertical = Symbol(name: "sliders-vertical")
    public static let smartphoneTablet = Symbol(name: "smartphone-tablet")
    public static let smartphone = Symbol(name: "smartphone")
    public static let smile = Symbol(name: "smile")
    public static let sparkles = Symbol(name: "sparkles")
    public static let speakerWaves = Symbol(name: "speaker-waves")
    public static let squareArrowAnticlockwise = Symbol(name: "square-arrow-anticlockwise")
    public static let squareArrowClockwise = Symbol(name: "square-arrow-clockwise")
    public static let squareArrowDownLeft = Symbol(name: "square-arrow-down-left")
    public static let squareArrowOutUpRight = Symbol(name: "square-arrow-out-up-right")
    public static let squareCornersFace = Symbol(name: "square-corners-face")
    public static let squareSplitTop = Symbol(name: "square-split-top")
    public static let square = Symbol(name: "square")
    public static let squaresFour = Symbol(name: "squares-four")
    public static let squaresStackedCheck = Symbol(name: "squares-stacked-check")
    public static let squaresStackedPlus = Symbol(name: "squares-stacked-plus")
    public static let squaresStacked = Symbol(name: "squares-stacked")
    public static let star = Symbol(name: "star")
    public static let store = Symbol(name: "store")
    public static let strikethrough = Symbol(name: "strikethrough")
    public static let sun = Symbol(name: "sun")
    public static let tag = Symbol(name: "tag")
    public static let textAlignCenter = Symbol(name: "text-align-center")
    public static let textAlignLeft = Symbol(name: "text-align-left")
    public static let textAlignRight = Symbol(name: "text-align-right")
    public static let textX = Symbol(name: "text-x")
    public static let text = Symbol(name: "text")
    public static let thumbsDown = Symbol(name: "thumbs-down")
    public static let thumbsUp = Symbol(name: "thumbs-up")
    public static let toggleCase = Symbol(name: "toggle-case")
    public static let toolCase = Symbol(name: "tool-case")
    public static let trash = Symbol(name: "trash")
    public static let trayArrowDown = Symbol(name: "tray-arrow-down")
    public static let trayArrowUp = Symbol(name: "tray-arrow-up")
    public static let treePalm = Symbol(name: "tree-palm")
    public static let triangleExclamationMark = Symbol(name: "triangle-exclamation-mark")
    public static let underline = Symbol(name: "underline")
    public static let userCog = Symbol(name: "user-cog")
    public static let userCross = Symbol(name: "user-cross")
    public static let userKey = Symbol(name: "user-key")
    public static let userLock = Symbol(name: "user-lock")
    public static let userMagnifyingGlass = Symbol(name: "user-magnifying-glass")
    public static let userMinus = Symbol(name: "user-minus")
    public static let userPen = Symbol(name: "user-pen")
    public static let userPlus = Symbol(name: "user-plus")
    public static let userStar = Symbol(name: "user-star")
    public static let user = Symbol(name: "user")
    public static let usersStacked = Symbol(name: "users-stacked")
    public static let videoCamera = Symbol(name: "video-camera")
    public static let waveArcsUp = Symbol(name: "wave-arcs-up")
    public static let waveform = Symbol(name: "waveform")
    public static let wrench = Symbol(name: "wrench")
}