/*
 Infomaniak Design System - iOS
 Copyright (C) 2026 Infomaniak Network SA

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Do not edit directly, this file was auto-generated.
 */

import SwiftUI

#if canImport(UIKit)
import UIKit
#endif

public struct ESDSSymbols: Sendable {
    private let name: String

    public var image: SwiftUI.Image {
        SwiftUI.Image(name, bundle: .module)
    }

    #if canImport(UIKit)
    public var uiImage: UIKit.UIImage {
        guard let image = UIKit.UIImage(named: name, in: .module, compatibleWith: nil) else {
            preconditionFailure("Missing symbol asset \"\(name)\".")
        }
        return image
    }
    #endif

    private init(name: String) {
        self.name = name
    }

    public static let aLargeSmall = ESDSSymbols(name: "a-large-small")
    public static let alarmClock = ESDSSymbols(name: "alarm-clock")
    public static let arrowDown = ESDSSymbols(name: "arrow-down")
    public static let arrowLeft = ESDSSymbols(name: "arrow-left")
    public static let arrowRight = ESDSSymbols(name: "arrow-right")
    public static let arrowTurnUpLeft = ESDSSymbols(name: "arrow-turn-up-left")
    public static let arrowTurnUpRight = ESDSSymbols(name: "arrow-turn-up-right")
    public static let arrowUpRight = ESDSSymbols(name: "arrow-up-right")
    public static let arrowUp = ESDSSymbols(name: "arrow-up")
    public static let arrowsCrossOut = ESDSSymbols(name: "arrows-cross-out")
    public static let arrowsFourDiagonalIn = ESDSSymbols(name: "arrows-four-diagonal-in")
    public static let arrowsFourDiagonalOut = ESDSSymbols(name: "arrows-four-diagonal-out")
    public static let arrowsTurnUpLeft = ESDSSymbols(name: "arrows-turn-up-left")
    public static let arrowsTwoDiagonalIn = ESDSSymbols(name: "arrows-two-diagonal-in")
    public static let arrowsUpDown = ESDSSymbols(name: "arrows-up-down")
    public static let atSign = ESDSSymbols(name: "at-sign")
    public static let bellSlash = ESDSSymbols(name: "bell-slash")
    public static let bell = ESDSSymbols(name: "bell")
    public static let bold = ESDSSymbols(name: "bold")
    public static let bookUser = ESDSSymbols(name: "book-user")
    public static let book = ESDSSymbols(name: "book")
    public static let bookmarkSlash = ESDSSymbols(name: "bookmark-slash")
    public static let bookmark = ESDSSymbols(name: "bookmark")
    public static let boxLid = ESDSSymbols(name: "box-lid")
    public static let briefcase = ESDSSymbols(name: "briefcase")
    public static let broom = ESDSSymbols(name: "broom")
    public static let bubbleLeftText = ESDSSymbols(name: "bubble-left-text")
    public static let bubbleTopRightCircle = ESDSSymbols(name: "bubble-top-right-circle")
    public static let bucketDrop = ESDSSymbols(name: "bucket-drop")
    public static let bug = ESDSSymbols(name: "bug")
    public static let building = ESDSSymbols(name: "building")
    public static let cakeCandles = ESDSSymbols(name: "cake-candles")
    public static let calendarCheck = ESDSSymbols(name: "calendar-check")
    public static let calendarCross = ESDSSymbols(name: "calendar-cross")
    public static let calendarDots = ESDSSymbols(name: "calendar-dots")
    public static let calendarNumberOne = ESDSSymbols(name: "calendar-number-one")
    public static let calendarPlus = ESDSSymbols(name: "calendar-plus")
    public static let calendarUser = ESDSSymbols(name: "calendar-user")
    public static let calendar = ESDSSymbols(name: "calendar")
    public static let cardUser = ESDSSymbols(name: "card-user")
    public static let check = ESDSSymbols(name: "check")
    public static let checkmarkList = ESDSSymbols(name: "checkmark-list")
    public static let chevronDown = ESDSSymbols(name: "chevron-down")
    public static let chevronLeftSlashChevronRight = ESDSSymbols(name: "chevron-left-slash-chevron-right")
    public static let chevronLeft = ESDSSymbols(name: "chevron-left")
    public static let chevronRight = ESDSSymbols(name: "chevron-right")
    public static let chevronUp = ESDSSymbols(name: "chevron-up")
    public static let chevronsLeftRight = ESDSSymbols(name: "chevrons-left-right")
    public static let chevronsUpDown = ESDSSymbols(name: "chevrons-up-down")
    public static let circleArrowAnticlockwise = ESDSSymbols(name: "circle-arrow-anticlockwise")
    public static let circleArrowClockwise = ESDSSymbols(name: "circle-arrow-clockwise")
    public static let circleArrowLeft = ESDSSymbols(name: "circle-arrow-left")
    public static let circleArrowRight = ESDSSymbols(name: "circle-arrow-right")
    public static let circleArrowsAnticlockwise = ESDSSymbols(name: "circle-arrows-anticlockwise")
    public static let circleCheckFilled = ESDSSymbols(name: "circle-check-filled")
    public static let circleCheck = ESDSSymbols(name: "circle-check")
    public static let circleCrossFilled = ESDSSymbols(name: "circle-cross-filled")
    public static let circleCross = ESDSSymbols(name: "circle-cross")
    public static let circleEllipsis = ESDSSymbols(name: "circle-ellipsis")
    public static let circleFadingArrowUp = ESDSSymbols(name: "circle-fading-arrow-up")
    public static let circleFilled = ESDSSymbols(name: "circle-filled")
    public static let circleInfoFilled = ESDSSymbols(name: "circle-info-filled")
    public static let circleInfo = ESDSSymbols(name: "circle-info")
    public static let circleLineCircle = ESDSSymbols(name: "circle-line-circle")
    public static let circleOpenTopRight = ESDSSymbols(name: "circle-open-top-right")
    public static let circlePlus = ESDSSymbols(name: "circle-plus")
    public static let circleQuestionFilled = ESDSSymbols(name: "circle-question-filled")
    public static let circleQuestion = ESDSSymbols(name: "circle-question")
    public static let circleUser = ESDSSymbols(name: "circle-user")
    public static let circle = ESDSSymbols(name: "circle")
    public static let circularArrowsClockwise = ESDSSymbols(name: "circular-arrows-clockwise")
    public static let clipboardArrowLeft = ESDSSymbols(name: "clipboard-arrow-left")
    public static let clock = ESDSSymbols(name: "clock")
    public static let cloudArrowAnticlockwise = ESDSSymbols(name: "cloud-arrow-anticlockwise")
    public static let cloudArrowDown = ESDSSymbols(name: "cloud-arrow-down")
    public static let cloudArrowUp = ESDSSymbols(name: "cloud-arrow-up")
    public static let cloudCheck = ESDSSymbols(name: "cloud-check")
    public static let cloudExclamationMark = ESDSSymbols(name: "cloud-exclamation-mark")
    public static let cloudSlash = ESDSSymbols(name: "cloud-slash")
    public static let cloud = ESDSSymbols(name: "cloud")
    public static let cog = ESDSSymbols(name: "cog")
    public static let columnsFour = ESDSSymbols(name: "columns-four")
    public static let columnsThree = ESDSSymbols(name: "columns-three")
    public static let concentricCircles = ESDSSymbols(name: "concentric-circles")
    public static let cornerBrackets = ESDSSymbols(name: "corner-brackets")
    public static let cross = ESDSSymbols(name: "cross")
    public static let crown = ESDSSymbols(name: "crown")
    public static let diamondsStackedVertical = ESDSSymbols(name: "diamonds-stacked-vertical")
    public static let doorOpen = ESDSSymbols(name: "door-open")
    public static let dotsList = ESDSSymbols(name: "dots-list")
    public static let dotsNine = ESDSSymbols(name: "dots-nine")
    public static let dotsSixHorizontal = ESDSSymbols(name: "dots-six-horizontal")
    public static let dotsSixVertical = ESDSSymbols(name: "dots-six-vertical")
    public static let dotsThreeHorizontal = ESDSSymbols(name: "dots-three-horizontal")
    public static let dotsThreeVertical = ESDSSymbols(name: "dots-three-vertical")
    public static let doubleQuotesClosing = ESDSSymbols(name: "double-quotes-closing")
    public static let envelopeCross = ESDSSymbols(name: "envelope-cross")
    public static let envelopeExclamationMark = ESDSSymbols(name: "envelope-exclamation-mark")
    public static let envelopeFilled = ESDSSymbols(name: "envelope-filled")
    public static let envelopeMagnifyingGlass = ESDSSymbols(name: "envelope-magnifying-glass")
    public static let envelopeMinus = ESDSSymbols(name: "envelope-minus")
    public static let envelopeOpen = ESDSSymbols(name: "envelope-open")
    public static let envelopePlus = ESDSSymbols(name: "envelope-plus")
    public static let envelopeQuestionMark = ESDSSymbols(name: "envelope-question-mark")
    public static let envelope = ESDSSymbols(name: "envelope")
    public static let eyeClosed = ESDSSymbols(name: "eye-closed")
    public static let eyeSlash = ESDSSymbols(name: "eye-slash")
    public static let eye = ESDSSymbols(name: "eye")
    public static let fileBraces = ESDSSymbols(name: "file-braces")
    public static let fileBulletLines = ESDSSymbols(name: "file-bullet-lines")
    public static let fileChart = ESDSSymbols(name: "file-chart")
    public static let fileSunMountain = ESDSSymbols(name: "file-sun-mountain")
    public static let fileText = ESDSSymbols(name: "file-text")
    public static let fileZipper = ESDSSymbols(name: "file-zipper")
    public static let file = ESDSSymbols(name: "file")
    public static let flag = ESDSSymbols(name: "flag")
    public static let folderCross = ESDSSymbols(name: "folder-cross")
    public static let folderOpen = ESDSSymbols(name: "folder-open")
    public static let folderPlus = ESDSSymbols(name: "folder-plus")
    public static let folder = ESDSSymbols(name: "folder")
    public static let frameSunMountainPlus = ESDSSymbols(name: "frame-sun-mountain-plus")
    public static let frameSunMountain = ESDSSymbols(name: "frame-sun-mountain")
    public static let funnel = ESDSSymbols(name: "funnel")
    public static let globe = ESDSSymbols(name: "globe")
    public static let gridThreeTwo = ESDSSymbols(name: "grid-three-two")
    public static let handshakeHeart = ESDSSymbols(name: "handshake-heart")
    public static let handshake = ESDSSymbols(name: "handshake")
    public static let hardDriveFilled = ESDSSymbols(name: "hard-drive-filled")
    public static let hardDrive = ESDSSymbols(name: "hard-drive")
    public static let hashSign = ESDSSymbols(name: "hash-sign")
    public static let heading1 = ESDSSymbols(name: "heading-1")
    public static let heading2 = ESDSSymbols(name: "heading-2")
    public static let heading3 = ESDSSymbols(name: "heading-3")
    public static let heading4 = ESDSSymbols(name: "heading-4")
    public static let headset = ESDSSymbols(name: "headset")
    public static let heart = ESDSSymbols(name: "heart")
    public static let highlighter = ESDSSymbols(name: "highlighter")
    public static let inbox = ESDSSymbols(name: "inbox")
    public static let isoCube = ESDSSymbols(name: "iso-cube")
    public static let italic = ESDSSymbols(name: "italic")
    public static let keyOptionApple = ESDSSymbols(name: "key-option-apple")
    public static let labelCross = ESDSSymbols(name: "label-cross")
    public static let languages = ESDSSymbols(name: "languages")
    public static let lightbulb = ESDSSymbols(name: "lightbulb")
    public static let linkBroken = ESDSSymbols(name: "link-broken")
    public static let linkHorizontal = ESDSSymbols(name: "link-horizontal")
    public static let link = ESDSSymbols(name: "link")
    public static let listFilter = ESDSSymbols(name: "list-filter")
    public static let listLeft = ESDSSymbols(name: "list-left")
    public static let listMagnifyingGlass = ESDSSymbols(name: "list-magnifying-glass")
    public static let list = ESDSSymbols(name: "list")
    public static let lockOpen = ESDSSymbols(name: "lock-open")
    public static let lock = ESDSSymbols(name: "lock")
    public static let loopedSquare = ESDSSymbols(name: "looped-square")
    public static let magnifyingGlassMinus = ESDSSymbols(name: "magnifying-glass-minus")
    public static let magnifyingGlassPlus = ESDSSymbols(name: "magnifying-glass-plus")
    public static let magnifyingGlass = ESDSSymbols(name: "magnifying-glass")
    public static let mapPin = ESDSSymbols(name: "map-pin")
    public static let megaphone = ESDSSymbols(name: "megaphone")
    public static let mic = ESDSSymbols(name: "mic")
    public static let minus = ESDSSymbols(name: "minus")
    public static let monitor = ESDSSymbols(name: "monitor")
    public static let moon = ESDSSymbols(name: "moon")
    public static let mousePointerSparkle = ESDSSymbols(name: "mouse-pointer-sparkle")
    public static let mousePointer = ESDSSymbols(name: "mouse-pointer")
    public static let musicNote = ESDSSymbols(name: "music-note")
    public static let network = ESDSSymbols(name: "network")
    public static let numberList = ESDSSymbols(name: "number-list")
    public static let paperPlane = ESDSSymbols(name: "paper-plane")
    public static let paperclip = ESDSSymbols(name: "paperclip")
    public static let pen = ESDSSymbols(name: "pen")
    public static let pencilSparkles = ESDSSymbols(name: "pencil-sparkles")
    public static let pieSlice = ESDSSymbols(name: "pie-slice")
    public static let pin = ESDSSymbols(name: "pin")
    public static let plus = ESDSSymbols(name: "plus")
    public static let power = ESDSSymbols(name: "power")
    public static let productCalendarFilled = ESDSSymbols(name: "product-calendar-filled")
    public static let productCalendar = ESDSSymbols(name: "product-calendar")
    public static let productContactFilled = ESDSSymbols(name: "product-contact-filled")
    public static let productContact = ESDSSymbols(name: "product-contact")
    public static let productEuriaFilled = ESDSSymbols(name: "product-euria-filled")
    public static let productEuria = ESDSSymbols(name: "product-euria")
    public static let productKchatFilled = ESDSSymbols(name: "product-kchat-filled")
    public static let productKchat = ESDSSymbols(name: "product-kchat")
    public static let productKdriveFilled = ESDSSymbols(name: "product-kdrive-filled")
    public static let productKdrive = ESDSSymbols(name: "product-kdrive")
    public static let productKmeetFilled = ESDSSymbols(name: "product-kmeet-filled")
    public static let productKmeet = ESDSSymbols(name: "product-kmeet")
    public static let productMailFilled = ESDSSymbols(name: "product-mail-filled")
    public static let productMail = ESDSSymbols(name: "product-mail")
    public static let productSwisstransferFilled = ESDSSymbols(name: "product-swisstransfer-filled")
    public static let productSwisstransfer = ESDSSymbols(name: "product-swisstransfer")
    public static let rectangleDotsThree = ESDSSymbols(name: "rectangle-dots-three")
    public static let rectangleDoubleOverline = ESDSSymbols(name: "rectangle-double-overline")
    public static let rectangleOverlineUnderline = ESDSSymbols(name: "rectangle-overline-underline")
    public static let rectangleSquaresTwo = ESDSSymbols(name: "rectangle-squares-two")
    public static let rectangleTwo = ESDSSymbols(name: "rectangle-two")
    public static let rectangleUnderlineDashed = ESDSSymbols(name: "rectangle-underline-dashed")
    public static let rocket = ESDSSymbols(name: "rocket")
    public static let rowsFour = ESDSSymbols(name: "rows-four")
    public static let rowsThree = ESDSSymbols(name: "rows-three")
    public static let rowsTwo = ESDSSymbols(name: "rows-two")
    public static let scissors = ESDSSymbols(name: "scissors")
    public static let share = ESDSSymbols(name: "share")
    public static let shieldCheck = ESDSSymbols(name: "shield-check")
    public static let shieldExclamationMark = ESDSSymbols(name: "shield-exclamation-mark")
    public static let shieldQuestionMark = ESDSSymbols(name: "shield-question-mark")
    public static let shieldUser = ESDSSymbols(name: "shield-user")
    public static let shoppingCart = ESDSSymbols(name: "shopping-cart")
    public static let sidebarLeftChevronLeft = ESDSSymbols(name: "sidebar-left-chevron-left")
    public static let sidebarLeftChevronRight = ESDSSymbols(name: "sidebar-left-chevron-right")
    public static let sidebarLeft = ESDSSymbols(name: "sidebar-left")
    public static let slash = ESDSSymbols(name: "slash")
    public static let slidersHorizontal = ESDSSymbols(name: "sliders-horizontal")
    public static let slidersVertical = ESDSSymbols(name: "sliders-vertical")
    public static let smartphoneTablet = ESDSSymbols(name: "smartphone-tablet")
    public static let smartphone = ESDSSymbols(name: "smartphone")
    public static let smile = ESDSSymbols(name: "smile")
    public static let sparkles = ESDSSymbols(name: "sparkles")
    public static let speakerWaves = ESDSSymbols(name: "speaker-waves")
    public static let squareArrowAnticlockwise = ESDSSymbols(name: "square-arrow-anticlockwise")
    public static let squareArrowClockwise = ESDSSymbols(name: "square-arrow-clockwise")
    public static let squareArrowDownLeft = ESDSSymbols(name: "square-arrow-down-left")
    public static let squareArrowOutUpRight = ESDSSymbols(name: "square-arrow-out-up-right")
    public static let squareCornersFace = ESDSSymbols(name: "square-corners-face")
    public static let squareSplitTop = ESDSSymbols(name: "square-split-top")
    public static let square = ESDSSymbols(name: "square")
    public static let squaresFour = ESDSSymbols(name: "squares-four")
    public static let squaresStackedCheck = ESDSSymbols(name: "squares-stacked-check")
    public static let squaresStackedPlus = ESDSSymbols(name: "squares-stacked-plus")
    public static let squaresStacked = ESDSSymbols(name: "squares-stacked")
    public static let star = ESDSSymbols(name: "star")
    public static let store = ESDSSymbols(name: "store")
    public static let strikethrough = ESDSSymbols(name: "strikethrough")
    public static let sun = ESDSSymbols(name: "sun")
    public static let tag = ESDSSymbols(name: "tag")
    public static let textAlignCenter = ESDSSymbols(name: "text-align-center")
    public static let textAlignLeft = ESDSSymbols(name: "text-align-left")
    public static let textAlignRight = ESDSSymbols(name: "text-align-right")
    public static let textX = ESDSSymbols(name: "text-x")
    public static let text = ESDSSymbols(name: "text")
    public static let thumbsDown = ESDSSymbols(name: "thumbs-down")
    public static let thumbsUp = ESDSSymbols(name: "thumbs-up")
    public static let toggleCase = ESDSSymbols(name: "toggle-case")
    public static let toolCase = ESDSSymbols(name: "tool-case")
    public static let trash = ESDSSymbols(name: "trash")
    public static let trayArrowDown = ESDSSymbols(name: "tray-arrow-down")
    public static let trayArrowUp = ESDSSymbols(name: "tray-arrow-up")
    public static let treePalm = ESDSSymbols(name: "tree-palm")
    public static let triangleExclamationMark = ESDSSymbols(name: "triangle-exclamation-mark")
    public static let triangleRight = ESDSSymbols(name: "triangle-right")
    public static let underline = ESDSSymbols(name: "underline")
    public static let userCog = ESDSSymbols(name: "user-cog")
    public static let userCross = ESDSSymbols(name: "user-cross")
    public static let userKey = ESDSSymbols(name: "user-key")
    public static let userLock = ESDSSymbols(name: "user-lock")
    public static let userMagnifyingGlass = ESDSSymbols(name: "user-magnifying-glass")
    public static let userMinus = ESDSSymbols(name: "user-minus")
    public static let userPen = ESDSSymbols(name: "user-pen")
    public static let userPlus = ESDSSymbols(name: "user-plus")
    public static let userStar = ESDSSymbols(name: "user-star")
    public static let user = ESDSSymbols(name: "user")
    public static let usersStacked = ESDSSymbols(name: "users-stacked")
    public static let videoCamera = ESDSSymbols(name: "video-camera")
    public static let waveArcsUp = ESDSSymbols(name: "wave-arcs-up")
    public static let waveform = ESDSSymbols(name: "waveform")
    public static let wrench = ESDSSymbols(name: "wrench")
    public static let zigzagArrowUpRight = ESDSSymbols(name: "zigzag-arrow-up-right")
}
