/*
 Infomaniak Design System - iOS
 Copyright (C) 2026 Infomaniak Network SA

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Do not edit directly, this file was auto-generated.
 */

import SwiftUI

public extension PrimitiveToken {
    enum Color: Sendable {
        static public let red50: SwiftUI.Color = SwiftUI.Color("red50", bundle: .module)
        static public let red100: SwiftUI.Color = SwiftUI.Color("red100", bundle: .module)
        static public let red200: SwiftUI.Color = SwiftUI.Color("red200", bundle: .module)
        static public let red300: SwiftUI.Color = SwiftUI.Color("red300", bundle: .module)
        static public let red400: SwiftUI.Color = SwiftUI.Color("red400", bundle: .module)
        static public let red500: SwiftUI.Color = SwiftUI.Color("red500", bundle: .module)
        static public let red600: SwiftUI.Color = SwiftUI.Color("red600", bundle: .module)
        static public let red700: SwiftUI.Color = SwiftUI.Color("red700", bundle: .module)
        static public let red800: SwiftUI.Color = SwiftUI.Color("red800", bundle: .module)
        static public let red900: SwiftUI.Color = SwiftUI.Color("red900", bundle: .module)
        static public let red950: SwiftUI.Color = SwiftUI.Color("red950", bundle: .module)
        static public let gray50: SwiftUI.Color = SwiftUI.Color("gray50", bundle: .module)
        static public let gray100: SwiftUI.Color = SwiftUI.Color("gray100", bundle: .module)
        static public let gray200: SwiftUI.Color = SwiftUI.Color("gray200", bundle: .module)
        static public let gray300: SwiftUI.Color = SwiftUI.Color("gray300", bundle: .module)
        static public let gray400: SwiftUI.Color = SwiftUI.Color("gray400", bundle: .module)
        static public let gray500: SwiftUI.Color = SwiftUI.Color("gray500", bundle: .module)
        static public let gray600: SwiftUI.Color = SwiftUI.Color("gray600", bundle: .module)
        static public let gray700: SwiftUI.Color = SwiftUI.Color("gray700", bundle: .module)
        static public let gray800: SwiftUI.Color = SwiftUI.Color("gray800", bundle: .module)
        static public let gray900: SwiftUI.Color = SwiftUI.Color("gray900", bundle: .module)
        static public let gray950: SwiftUI.Color = SwiftUI.Color("gray950", bundle: .module)
        static public let gray40010: SwiftUI.Color = SwiftUI.Color("gray400-10", bundle: .module)
        static public let gray95010: SwiftUI.Color = SwiftUI.Color("gray950-10", bundle: .module)
        static public let gray4006: SwiftUI.Color = SwiftUI.Color("gray400-6", bundle: .module)
        static public let gray4008: SwiftUI.Color = SwiftUI.Color("gray400-8", bundle: .module)
        static public let gray40014: SwiftUI.Color = SwiftUI.Color("gray400-14", bundle: .module)
        static public let gray95014: SwiftUI.Color = SwiftUI.Color("gray950-14", bundle: .module)
        static public let gray9506: SwiftUI.Color = SwiftUI.Color("gray950-6", bundle: .module)
        static public let gray9508: SwiftUI.Color = SwiftUI.Color("gray950-8", bundle: .module)
        static public let pink50: SwiftUI.Color = SwiftUI.Color("pink50", bundle: .module)
        static public let pink100: SwiftUI.Color = SwiftUI.Color("pink100", bundle: .module)
        static public let pink200: SwiftUI.Color = SwiftUI.Color("pink200", bundle: .module)
        static public let pink300: SwiftUI.Color = SwiftUI.Color("pink300", bundle: .module)
        static public let pink400: SwiftUI.Color = SwiftUI.Color("pink400", bundle: .module)
        static public let pink500: SwiftUI.Color = SwiftUI.Color("pink500", bundle: .module)
        static public let pink600: SwiftUI.Color = SwiftUI.Color("pink600", bundle: .module)
        static public let pink700: SwiftUI.Color = SwiftUI.Color("pink700", bundle: .module)
        static public let pink800: SwiftUI.Color = SwiftUI.Color("pink800", bundle: .module)
        static public let pink900: SwiftUI.Color = SwiftUI.Color("pink900", bundle: .module)
        static public let pink950: SwiftUI.Color = SwiftUI.Color("pink950", bundle: .module)
        static public let blue50: SwiftUI.Color = SwiftUI.Color("blue50", bundle: .module)
        static public let blue100: SwiftUI.Color = SwiftUI.Color("blue100", bundle: .module)
        static public let blue200: SwiftUI.Color = SwiftUI.Color("blue200", bundle: .module)
        static public let blue300: SwiftUI.Color = SwiftUI.Color("blue300", bundle: .module)
        static public let blue400: SwiftUI.Color = SwiftUI.Color("blue400", bundle: .module)
        static public let blue500: SwiftUI.Color = SwiftUI.Color("blue500", bundle: .module)
        static public let blue600: SwiftUI.Color = SwiftUI.Color("blue600", bundle: .module)
        static public let blue700: SwiftUI.Color = SwiftUI.Color("blue700", bundle: .module)
        static public let blue800: SwiftUI.Color = SwiftUI.Color("blue800", bundle: .module)
        static public let blue900: SwiftUI.Color = SwiftUI.Color("blue900", bundle: .module)
        static public let blue950: SwiftUI.Color = SwiftUI.Color("blue950", bundle: .module)
        static public let black: SwiftUI.Color = SwiftUI.Color("black", bundle: .module)
        static public let white: SwiftUI.Color = SwiftUI.Color("white", bundle: .module)
        static public let purple50: SwiftUI.Color = SwiftUI.Color("purple50", bundle: .module)
        static public let purple100: SwiftUI.Color = SwiftUI.Color("purple100", bundle: .module)
        static public let purple200: SwiftUI.Color = SwiftUI.Color("purple200", bundle: .module)
        static public let purple300: SwiftUI.Color = SwiftUI.Color("purple300", bundle: .module)
        static public let purple400: SwiftUI.Color = SwiftUI.Color("purple400", bundle: .module)
        static public let purple500: SwiftUI.Color = SwiftUI.Color("purple500", bundle: .module)
        static public let purple600: SwiftUI.Color = SwiftUI.Color("purple600", bundle: .module)
        static public let purple700: SwiftUI.Color = SwiftUI.Color("purple700", bundle: .module)
        static public let purple800: SwiftUI.Color = SwiftUI.Color("purple800", bundle: .module)
        static public let purple900: SwiftUI.Color = SwiftUI.Color("purple900", bundle: .module)
        static public let purple950: SwiftUI.Color = SwiftUI.Color("purple950", bundle: .module)
        static public let orange50: SwiftUI.Color = SwiftUI.Color("orange50", bundle: .module)
        static public let orange100: SwiftUI.Color = SwiftUI.Color("orange100", bundle: .module)
        static public let orange200: SwiftUI.Color = SwiftUI.Color("orange200", bundle: .module)
        static public let orange300: SwiftUI.Color = SwiftUI.Color("orange300", bundle: .module)
        static public let orange400: SwiftUI.Color = SwiftUI.Color("orange400", bundle: .module)
        static public let orange500: SwiftUI.Color = SwiftUI.Color("orange500", bundle: .module)
        static public let orange600: SwiftUI.Color = SwiftUI.Color("orange600", bundle: .module)
        static public let orange700: SwiftUI.Color = SwiftUI.Color("orange700", bundle: .module)
        static public let orange800: SwiftUI.Color = SwiftUI.Color("orange800", bundle: .module)
        static public let orange900: SwiftUI.Color = SwiftUI.Color("orange900", bundle: .module)
        static public let orange950: SwiftUI.Color = SwiftUI.Color("orange950", bundle: .module)
        static public let lime50: SwiftUI.Color = SwiftUI.Color("lime50", bundle: .module)
        static public let lime100: SwiftUI.Color = SwiftUI.Color("lime100", bundle: .module)
        static public let lime200: SwiftUI.Color = SwiftUI.Color("lime200", bundle: .module)
        static public let lime300: SwiftUI.Color = SwiftUI.Color("lime300", bundle: .module)
        static public let lime400: SwiftUI.Color = SwiftUI.Color("lime400", bundle: .module)
        static public let lime500: SwiftUI.Color = SwiftUI.Color("lime500", bundle: .module)
        static public let lime600: SwiftUI.Color = SwiftUI.Color("lime600", bundle: .module)
        static public let lime700: SwiftUI.Color = SwiftUI.Color("lime700", bundle: .module)
        static public let lime800: SwiftUI.Color = SwiftUI.Color("lime800", bundle: .module)
        static public let lime900: SwiftUI.Color = SwiftUI.Color("lime900", bundle: .module)
        static public let lime950: SwiftUI.Color = SwiftUI.Color("lime950", bundle: .module)
        static public let cyan50: SwiftUI.Color = SwiftUI.Color("cyan50", bundle: .module)
        static public let cyan100: SwiftUI.Color = SwiftUI.Color("cyan100", bundle: .module)
        static public let cyan200: SwiftUI.Color = SwiftUI.Color("cyan200", bundle: .module)
        static public let cyan300: SwiftUI.Color = SwiftUI.Color("cyan300", bundle: .module)
        static public let cyan400: SwiftUI.Color = SwiftUI.Color("cyan400", bundle: .module)
        static public let cyan500: SwiftUI.Color = SwiftUI.Color("cyan500", bundle: .module)
        static public let cyan600: SwiftUI.Color = SwiftUI.Color("cyan600", bundle: .module)
        static public let cyan700: SwiftUI.Color = SwiftUI.Color("cyan700", bundle: .module)
        static public let cyan800: SwiftUI.Color = SwiftUI.Color("cyan800", bundle: .module)
        static public let cyan900: SwiftUI.Color = SwiftUI.Color("cyan900", bundle: .module)
        static public let cyan950: SwiftUI.Color = SwiftUI.Color("cyan950", bundle: .module)
        static public let indigo50: SwiftUI.Color = SwiftUI.Color("indigo50", bundle: .module)
        static public let indigo100: SwiftUI.Color = SwiftUI.Color("indigo100", bundle: .module)
        static public let indigo200: SwiftUI.Color = SwiftUI.Color("indigo200", bundle: .module)
        static public let indigo300: SwiftUI.Color = SwiftUI.Color("indigo300", bundle: .module)
        static public let indigo400: SwiftUI.Color = SwiftUI.Color("indigo400", bundle: .module)
        static public let indigo500: SwiftUI.Color = SwiftUI.Color("indigo500", bundle: .module)
        static public let indigo600: SwiftUI.Color = SwiftUI.Color("indigo600", bundle: .module)
        static public let indigo700: SwiftUI.Color = SwiftUI.Color("indigo700", bundle: .module)
        static public let indigo800: SwiftUI.Color = SwiftUI.Color("indigo800", bundle: .module)
        static public let indigo900: SwiftUI.Color = SwiftUI.Color("indigo900", bundle: .module)
        static public let indigo950: SwiftUI.Color = SwiftUI.Color("indigo950", bundle: .module)
        static public let aqua50: SwiftUI.Color = SwiftUI.Color("aqua50", bundle: .module)
        static public let aqua100: SwiftUI.Color = SwiftUI.Color("aqua100", bundle: .module)
        static public let aqua200: SwiftUI.Color = SwiftUI.Color("aqua200", bundle: .module)
        static public let aqua300: SwiftUI.Color = SwiftUI.Color("aqua300", bundle: .module)
        static public let aqua400: SwiftUI.Color = SwiftUI.Color("aqua400", bundle: .module)
        static public let aqua500: SwiftUI.Color = SwiftUI.Color("aqua500", bundle: .module)
        static public let aqua600: SwiftUI.Color = SwiftUI.Color("aqua600", bundle: .module)
        static public let aqua700: SwiftUI.Color = SwiftUI.Color("aqua700", bundle: .module)
        static public let aqua800: SwiftUI.Color = SwiftUI.Color("aqua800", bundle: .module)
        static public let aqua900: SwiftUI.Color = SwiftUI.Color("aqua900", bundle: .module)
        static public let aqua950: SwiftUI.Color = SwiftUI.Color("aqua950", bundle: .module)
        static public let violet50: SwiftUI.Color = SwiftUI.Color("violet50", bundle: .module)
        static public let violet100: SwiftUI.Color = SwiftUI.Color("violet100", bundle: .module)
        static public let violet200: SwiftUI.Color = SwiftUI.Color("violet200", bundle: .module)
        static public let violet300: SwiftUI.Color = SwiftUI.Color("violet300", bundle: .module)
        static public let violet400: SwiftUI.Color = SwiftUI.Color("violet400", bundle: .module)
        static public let violet500: SwiftUI.Color = SwiftUI.Color("violet500", bundle: .module)
        static public let violet600: SwiftUI.Color = SwiftUI.Color("violet600", bundle: .module)
        static public let violet700: SwiftUI.Color = SwiftUI.Color("violet700", bundle: .module)
        static public let violet800: SwiftUI.Color = SwiftUI.Color("violet800", bundle: .module)
        static public let violet900: SwiftUI.Color = SwiftUI.Color("violet900", bundle: .module)
        static public let violet950: SwiftUI.Color = SwiftUI.Color("violet950", bundle: .module)
        static public let coral50: SwiftUI.Color = SwiftUI.Color("coral50", bundle: .module)
        static public let coral100: SwiftUI.Color = SwiftUI.Color("coral100", bundle: .module)
        static public let coral200: SwiftUI.Color = SwiftUI.Color("coral200", bundle: .module)
        static public let coral300: SwiftUI.Color = SwiftUI.Color("coral300", bundle: .module)
        static public let coral400: SwiftUI.Color = SwiftUI.Color("coral400", bundle: .module)
        static public let coral500: SwiftUI.Color = SwiftUI.Color("coral500", bundle: .module)
        static public let coral600: SwiftUI.Color = SwiftUI.Color("coral600", bundle: .module)
        static public let coral700: SwiftUI.Color = SwiftUI.Color("coral700", bundle: .module)
        static public let coral800: SwiftUI.Color = SwiftUI.Color("coral800", bundle: .module)
        static public let coral900: SwiftUI.Color = SwiftUI.Color("coral900", bundle: .module)
        static public let coral950: SwiftUI.Color = SwiftUI.Color("coral950", bundle: .module)
        static public let ocean50: SwiftUI.Color = SwiftUI.Color("ocean50", bundle: .module)
        static public let ocean100: SwiftUI.Color = SwiftUI.Color("ocean100", bundle: .module)
        static public let ocean200: SwiftUI.Color = SwiftUI.Color("ocean200", bundle: .module)
        static public let ocean300: SwiftUI.Color = SwiftUI.Color("ocean300", bundle: .module)
        static public let ocean400: SwiftUI.Color = SwiftUI.Color("ocean400", bundle: .module)
        static public let ocean500: SwiftUI.Color = SwiftUI.Color("ocean500", bundle: .module)
        static public let ocean600: SwiftUI.Color = SwiftUI.Color("ocean600", bundle: .module)
        static public let ocean700: SwiftUI.Color = SwiftUI.Color("ocean700", bundle: .module)
        static public let ocean800: SwiftUI.Color = SwiftUI.Color("ocean800", bundle: .module)
        static public let ocean900: SwiftUI.Color = SwiftUI.Color("ocean900", bundle: .module)
        static public let ocean950: SwiftUI.Color = SwiftUI.Color("ocean950", bundle: .module)
        static public let emerald50: SwiftUI.Color = SwiftUI.Color("emerald50", bundle: .module)
        static public let emerald100: SwiftUI.Color = SwiftUI.Color("emerald100", bundle: .module)
        static public let emerald200: SwiftUI.Color = SwiftUI.Color("emerald200", bundle: .module)
        static public let emerald300: SwiftUI.Color = SwiftUI.Color("emerald300", bundle: .module)
        static public let emerald400: SwiftUI.Color = SwiftUI.Color("emerald400", bundle: .module)
        static public let emerald500: SwiftUI.Color = SwiftUI.Color("emerald500", bundle: .module)
        static public let emerald600: SwiftUI.Color = SwiftUI.Color("emerald600", bundle: .module)
        static public let emerald700: SwiftUI.Color = SwiftUI.Color("emerald700", bundle: .module)
        static public let emerald800: SwiftUI.Color = SwiftUI.Color("emerald800", bundle: .module)
        static public let emerald900: SwiftUI.Color = SwiftUI.Color("emerald900", bundle: .module)
        static public let emerald950: SwiftUI.Color = SwiftUI.Color("emerald950", bundle: .module)
        static public let yellow50: SwiftUI.Color = SwiftUI.Color("yellow50", bundle: .module)
        static public let yellow100: SwiftUI.Color = SwiftUI.Color("yellow100", bundle: .module)
        static public let yellow200: SwiftUI.Color = SwiftUI.Color("yellow200", bundle: .module)
        static public let yellow300: SwiftUI.Color = SwiftUI.Color("yellow300", bundle: .module)
        static public let yellow400: SwiftUI.Color = SwiftUI.Color("yellow400", bundle: .module)
        static public let yellow500: SwiftUI.Color = SwiftUI.Color("yellow500", bundle: .module)
        static public let yellow600: SwiftUI.Color = SwiftUI.Color("yellow600", bundle: .module)
        static public let yellow700: SwiftUI.Color = SwiftUI.Color("yellow700", bundle: .module)
        static public let yellow800: SwiftUI.Color = SwiftUI.Color("yellow800", bundle: .module)
        static public let yellow900: SwiftUI.Color = SwiftUI.Color("yellow900", bundle: .module)
        static public let yellow950: SwiftUI.Color = SwiftUI.Color("yellow950", bundle: .module)
        static public let transparent: SwiftUI.Color = SwiftUI.Color("transparent", bundle: .module)
    }
}