/*
 Infomaniak Design System - iOS
 Copyright (C) 2026 Infomaniak Network SA

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 Do not edit directly, this file was auto-generated.
 */

import ESDSFoundation
import ESDSPrimitives
import SwiftUI

extension ESDSTheme.Color {
    static let security = ESDSTheme.Color(
        backgroundBrand: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple300),
        backgroundBrandCalendar: SwiftUI.Color(light: PrimitiveToken.Color.aqua500, dark: PrimitiveToken.Color.aqua300),
        backgroundBrandContacts: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet300),
        backgroundBrandEuria: SwiftUI.Color(light: PrimitiveToken.Color.ocean700, dark: PrimitiveToken.Color.ocean400),
        backgroundBrandInfomaniak: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue400),
        backgroundBrandKchat: SwiftUI.Color(light: PrimitiveToken.Color.cyan600, dark: PrimitiveToken.Color.cyan300),
        backgroundBrandKdrive: SwiftUI.Color(light: PrimitiveToken.Color.indigo500, dark: PrimitiveToken.Color.indigo300),
        backgroundBrandKnote: SwiftUI.Color(light: PrimitiveToken.Color.coral600, dark: PrimitiveToken.Color.coral300),
        backgroundBrandMail: SwiftUI.Color(light: PrimitiveToken.Color.pink600, dark: PrimitiveToken.Color.pink300),
        backgroundBrandSecurity: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple300),
        backgroundBrandSwisstransfer: SwiftUI.Color(
            light: PrimitiveToken.Color.emerald600,
            dark: PrimitiveToken.Color.emerald300
        ),
        backgroundDatavizBlueDim1: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue400),
        backgroundDatavizBlueDim2: SwiftUI.Color(light: PrimitiveToken.Color.blue200, dark: PrimitiveToken.Color.blue800),
        backgroundDatavizDim1: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue600),
        backgroundDatavizDim2: SwiftUI.Color(light: PrimitiveToken.Color.blue200, dark: PrimitiveToken.Color.blue200),
        backgroundDatavizEmeraldDim1: SwiftUI.Color(
            light: PrimitiveToken.Color.emerald600,
            dark: PrimitiveToken.Color.emerald400
        ),
        backgroundDatavizEmeraldDim2: SwiftUI.Color(
            light: PrimitiveToken.Color.emerald200,
            dark: PrimitiveToken.Color.emerald800
        ),
        backgroundDatavizGrayDim1: SwiftUI.Color(light: PrimitiveToken.Color.gray500, dark: PrimitiveToken.Color.gray400),
        backgroundDatavizGrayDim2: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray800),
        backgroundDatavizOrangeDim1: SwiftUI.Color(light: PrimitiveToken.Color.orange600, dark: PrimitiveToken.Color.orange400),
        backgroundDatavizOrangeDim2: SwiftUI.Color(light: PrimitiveToken.Color.orange200, dark: PrimitiveToken.Color.orange800),
        backgroundDatavizPinkDim1: SwiftUI.Color(light: PrimitiveToken.Color.pink600, dark: PrimitiveToken.Color.pink400),
        backgroundDatavizPinkDim2: SwiftUI.Color(light: PrimitiveToken.Color.pink200, dark: PrimitiveToken.Color.pink800),
        backgroundDatavizPurpleDim1: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple400),
        backgroundDatavizPurpleDim2: SwiftUI.Color(light: PrimitiveToken.Color.purple200, dark: PrimitiveToken.Color.purple800),
        backgroundDatavizVioletDim1: SwiftUI.Color(light: PrimitiveToken.Color.violet600, dark: PrimitiveToken.Color.violet400),
        backgroundDatavizVioletDim2: SwiftUI.Color(light: PrimitiveToken.Color.violet200, dark: PrimitiveToken.Color.violet800),
        backgroundDatavizYellowDim1: SwiftUI.Color(light: PrimitiveToken.Color.yellow500, dark: PrimitiveToken.Color.yellow400),
        backgroundDatavizYellowDim2: SwiftUI.Color(light: PrimitiveToken.Color.yellow200, dark: PrimitiveToken.Color.yellow800),
        backgroundDisabled: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray800),
        backgroundElevationOverlay: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray800),
        backgroundElevationRaised: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.gray800),
        backgroundElevationSunken: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray950),
        backgroundElevationSurface: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.gray800),
        backgroundFeedbackErrorDim1: SwiftUI.Color(light: PrimitiveToken.Color.red400, dark: PrimitiveToken.Color.red300),
        backgroundFeedbackErrorDim2: SwiftUI.Color(light: PrimitiveToken.Color.red200, dark: PrimitiveToken.Color.red900),
        backgroundFeedbackSuccessDim1: SwiftUI.Color(light: PrimitiveToken.Color.lime500, dark: PrimitiveToken.Color.lime400),
        backgroundFeedbackSuccessDim2: SwiftUI.Color(light: PrimitiveToken.Color.lime200, dark: PrimitiveToken.Color.lime900),
        backgroundFeedbackWarningDim1: SwiftUI.Color(light: PrimitiveToken.Color.orange400, dark: PrimitiveToken.Color.orange300),
        backgroundFeedbackWarningDim2: SwiftUI.Color(light: PrimitiveToken.Color.orange200, dark: PrimitiveToken.Color.orange900),
        borderBrand: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple300),
        borderBrandCalendar: SwiftUI.Color(light: PrimitiveToken.Color.aqua500, dark: PrimitiveToken.Color.aqua300),
        borderBrandContacts: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet300),
        borderBrandEuria: SwiftUI.Color(light: PrimitiveToken.Color.ocean700, dark: PrimitiveToken.Color.ocean400),
        borderBrandInfomaniak: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue400),
        borderBrandKchat: SwiftUI.Color(light: PrimitiveToken.Color.cyan600, dark: PrimitiveToken.Color.cyan300),
        borderBrandKdrive: SwiftUI.Color(light: PrimitiveToken.Color.indigo500, dark: PrimitiveToken.Color.indigo300),
        borderBrandKnote: SwiftUI.Color(light: PrimitiveToken.Color.coral600, dark: PrimitiveToken.Color.coral300),
        borderBrandMail: SwiftUI.Color(light: PrimitiveToken.Color.pink600, dark: PrimitiveToken.Color.pink300),
        borderBrandSecurity: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple300),
        borderBrandSwisstransfer: SwiftUI.Color(light: PrimitiveToken.Color.emerald600, dark: PrimitiveToken.Color.emerald300),
        borderDatavizBlueDim1: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue400),
        borderDatavizBlueDim2: SwiftUI.Color(light: PrimitiveToken.Color.blue200, dark: PrimitiveToken.Color.blue700),
        borderDatavizDim1: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue600),
        borderDatavizDim2: SwiftUI.Color(light: PrimitiveToken.Color.blue200, dark: PrimitiveToken.Color.blue200),
        borderDatavizEmeraldDim1: SwiftUI.Color(light: PrimitiveToken.Color.emerald600, dark: PrimitiveToken.Color.emerald400),
        borderDatavizEmeraldDim2: SwiftUI.Color(light: PrimitiveToken.Color.emerald200, dark: PrimitiveToken.Color.emerald700),
        borderDatavizGrayDim1: SwiftUI.Color(light: PrimitiveToken.Color.gray600, dark: PrimitiveToken.Color.gray400),
        borderDatavizGrayDim2: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray700),
        borderDatavizOrangeDim1: SwiftUI.Color(light: PrimitiveToken.Color.orange600, dark: PrimitiveToken.Color.orange400),
        borderDatavizOrangeDim2: SwiftUI.Color(light: PrimitiveToken.Color.orange200, dark: PrimitiveToken.Color.orange700),
        borderDatavizPinkDim1: SwiftUI.Color(light: PrimitiveToken.Color.pink600, dark: PrimitiveToken.Color.pink400),
        borderDatavizPinkDim2: SwiftUI.Color(light: PrimitiveToken.Color.pink200, dark: PrimitiveToken.Color.pink700),
        borderDatavizPurpleDim1: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple400),
        borderDatavizPurpleDim2: SwiftUI.Color(light: PrimitiveToken.Color.purple200, dark: PrimitiveToken.Color.purple700),
        borderDatavizVioletDim1: SwiftUI.Color(light: PrimitiveToken.Color.violet600, dark: PrimitiveToken.Color.violet400),
        borderDatavizVioletDim2: SwiftUI.Color(light: PrimitiveToken.Color.violet200, dark: PrimitiveToken.Color.violet700),
        borderDatavizYellowDim1: SwiftUI.Color(light: PrimitiveToken.Color.yellow600, dark: PrimitiveToken.Color.yellow400),
        borderDatavizYellowDim2: SwiftUI.Color(light: PrimitiveToken.Color.yellow200, dark: PrimitiveToken.Color.yellow700),
        borderDim1: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        borderDim2: SwiftUI.Color(light: PrimitiveToken.Color.gray300, dark: PrimitiveToken.Color.gray600),
        borderDim3: SwiftUI.Color(light: PrimitiveToken.Color.gray200, dark: PrimitiveToken.Color.gray700),
        borderDim4: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray800),
        borderFeedbackErrorDim1: SwiftUI.Color(light: PrimitiveToken.Color.red600, dark: PrimitiveToken.Color.red400),
        borderFeedbackErrorDim2: SwiftUI.Color(light: PrimitiveToken.Color.red200, dark: PrimitiveToken.Color.red700),
        borderFeedbackSuccessDim1: SwiftUI.Color(light: PrimitiveToken.Color.lime600, dark: PrimitiveToken.Color.lime400),
        borderFeedbackSuccessDim2: SwiftUI.Color(light: PrimitiveToken.Color.lime200, dark: PrimitiveToken.Color.lime700),
        borderFeedbackWarningDim1: SwiftUI.Color(light: PrimitiveToken.Color.orange600, dark: PrimitiveToken.Color.orange400),
        borderFeedbackWarningDim2: SwiftUI.Color(light: PrimitiveToken.Color.orange200, dark: PrimitiveToken.Color.orange700),
        contentBrand: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple400),
        contentBrandCalendar: SwiftUI.Color(light: PrimitiveToken.Color.aqua700, dark: PrimitiveToken.Color.aqua400),
        contentBrandContacts: SwiftUI.Color(light: PrimitiveToken.Color.violet500, dark: PrimitiveToken.Color.violet300),
        contentBrandEuria: SwiftUI.Color(light: PrimitiveToken.Color.ocean600, dark: PrimitiveToken.Color.ocean400),
        contentBrandInfomaniak: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue400),
        contentBrandKchat: SwiftUI.Color(light: PrimitiveToken.Color.cyan600, dark: PrimitiveToken.Color.cyan400),
        contentBrandKdrive: SwiftUI.Color(light: PrimitiveToken.Color.indigo500, dark: PrimitiveToken.Color.indigo300),
        contentBrandKnote: SwiftUI.Color(light: PrimitiveToken.Color.coral600, dark: PrimitiveToken.Color.coral400),
        contentBrandMail: SwiftUI.Color(light: PrimitiveToken.Color.pink700, dark: PrimitiveToken.Color.pink400),
        contentBrandSecurity: SwiftUI.Color(light: PrimitiveToken.Color.purple600, dark: PrimitiveToken.Color.purple400),
        contentBrandSwisstransfer: SwiftUI.Color(light: PrimitiveToken.Color.emerald600, dark: PrimitiveToken.Color.emerald400),
        contentDisabled: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        contentFeedbackError: SwiftUI.Color(light: PrimitiveToken.Color.red700, dark: PrimitiveToken.Color.red300),
        contentFeedbackSuccess: SwiftUI.Color(light: PrimitiveToken.Color.lime700, dark: PrimitiveToken.Color.lime300),
        contentFeedbackWarning: SwiftUI.Color(light: PrimitiveToken.Color.orange700, dark: PrimitiveToken.Color.orange300),
        contentInverse: SwiftUI.Color(light: PrimitiveToken.Color.gray100, dark: PrimitiveToken.Color.gray800),
        contentMuted: SwiftUI.Color(light: PrimitiveToken.Color.gray500, dark: PrimitiveToken.Color.gray400),
        contentOnBrand: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.purple950),
        contentOnBrandCalendar: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.aqua950),
        contentOnBrandContacts: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.violet950),
        contentOnBrandEuria: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.ocean950),
        contentOnBrandInfomaniak: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.blue950),
        contentOnBrandKchat: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.cyan950),
        contentOnBrandKdrive: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.indigo950),
        contentOnBrandKnote: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.coral950),
        contentOnBrandMail: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.pink950),
        contentOnBrandSecurity: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.purple950),
        contentOnBrandSwisstransfer: SwiftUI.Color(light: PrimitiveToken.Color.white, dark: PrimitiveToken.Color.emerald950),
        contentOnDatavizBlueDim1: SwiftUI.Color(light: PrimitiveToken.Color.blue900, dark: PrimitiveToken.Color.blue100),
        contentOnDatavizBlueDim2: SwiftUI.Color(light: PrimitiveToken.Color.blue50, dark: PrimitiveToken.Color.blue950),
        contentOnDatavizDim1: SwiftUI.Color(light: PrimitiveToken.Color.blue900, dark: PrimitiveToken.Color.blue900),
        contentOnDatavizDim2: SwiftUI.Color(light: PrimitiveToken.Color.blue50, dark: PrimitiveToken.Color.blue50),
        contentOnDatavizEmeraldDim1: SwiftUI.Color(light: PrimitiveToken.Color.emerald900, dark: PrimitiveToken.Color.emerald100),
        contentOnDatavizEmeraldDim2: SwiftUI.Color(light: PrimitiveToken.Color.emerald50, dark: PrimitiveToken.Color.emerald950),
        contentOnDatavizGrayDim1: SwiftUI.Color(light: PrimitiveToken.Color.gray900, dark: PrimitiveToken.Color.gray100),
        contentOnDatavizGrayDim2: SwiftUI.Color(light: PrimitiveToken.Color.gray50, dark: PrimitiveToken.Color.gray950),
        contentOnDatavizOrangeDim1: SwiftUI.Color(light: PrimitiveToken.Color.orange900, dark: PrimitiveToken.Color.orange100),
        contentOnDatavizOrangeDim2: SwiftUI.Color(light: PrimitiveToken.Color.orange100, dark: PrimitiveToken.Color.orange950),
        contentOnDatavizPinkDim1: SwiftUI.Color(light: PrimitiveToken.Color.pink900, dark: PrimitiveToken.Color.pink100),
        contentOnDatavizPinkDim2: SwiftUI.Color(light: PrimitiveToken.Color.pink50, dark: PrimitiveToken.Color.pink950),
        contentOnDatavizPurpleDim1: SwiftUI.Color(light: PrimitiveToken.Color.purple900, dark: PrimitiveToken.Color.purple100),
        contentOnDatavizPurpleDim2: SwiftUI.Color(light: PrimitiveToken.Color.purple50, dark: PrimitiveToken.Color.purple950),
        contentOnDatavizVioletDim1: SwiftUI.Color(light: PrimitiveToken.Color.violet900, dark: PrimitiveToken.Color.violet100),
        contentOnDatavizVioletDim2: SwiftUI.Color(light: PrimitiveToken.Color.violet50, dark: PrimitiveToken.Color.violet950),
        contentOnDatavizYellowDim1: SwiftUI.Color(light: PrimitiveToken.Color.yellow900, dark: PrimitiveToken.Color.yellow100),
        contentOnDatavizYellowDim2: SwiftUI.Color(light: PrimitiveToken.Color.yellow50, dark: PrimitiveToken.Color.yellow950),
        contentOnDisabled: SwiftUI.Color(light: PrimitiveToken.Color.gray400, dark: PrimitiveToken.Color.gray500),
        contentOnFeedbackError: SwiftUI.Color(light: PrimitiveToken.Color.red900, dark: PrimitiveToken.Color.red100),
        contentOnFeedbackSuccess: SwiftUI.Color(light: PrimitiveToken.Color.lime950, dark: PrimitiveToken.Color.lime50),
        contentOnFeedbackWarning: SwiftUI.Color(light: PrimitiveToken.Color.orange900, dark: PrimitiveToken.Color.orange50),
        contentPrimary: SwiftUI.Color(light: PrimitiveToken.Color.gray800, dark: PrimitiveToken.Color.gray100),
        contentSecondary: SwiftUI.Color(light: PrimitiveToken.Color.gray700, dark: PrimitiveToken.Color.gray200),
        contentTertiary: SwiftUI.Color(light: PrimitiveToken.Color.gray600, dark: PrimitiveToken.Color.gray300),
        contentVisited: SwiftUI.Color(light: PrimitiveToken.Color.violet600, dark: PrimitiveToken.Color.violet300),
        shadow2xl: SwiftUI.Color(light: PrimitiveToken.Color.gray40014, dark: PrimitiveToken.Color.gray95014),
        shadowLg: SwiftUI.Color(light: PrimitiveToken.Color.gray40010, dark: PrimitiveToken.Color.gray95010),
        shadowMd: SwiftUI.Color(light: PrimitiveToken.Color.gray4008, dark: PrimitiveToken.Color.gray9508),
        shadowSm: SwiftUI.Color(light: PrimitiveToken.Color.gray4006, dark: PrimitiveToken.Color.gray9506),
        shadowXl: SwiftUI.Color(light: PrimitiveToken.Color.gray40010, dark: PrimitiveToken.Color.gray95010),
        shadowXs: SwiftUI.Color(light: PrimitiveToken.Color.gray4006, dark: PrimitiveToken.Color.gray9506),
        stateFocus: SwiftUI.Color(light: PrimitiveToken.Color.blue600, dark: PrimitiveToken.Color.blue400),
        stateHoverMedium: SwiftUI.Color(light: PrimitiveToken.Color.blue90012, dark: PrimitiveToken.Color.gray5012),
        stateHoverStrong: SwiftUI.Color(light: PrimitiveToken.Color.blue90060, dark: PrimitiveToken.Color.gray5020),
        statePressedMedium: SwiftUI.Color(light: PrimitiveToken.Color.blue90016, dark: PrimitiveToken.Color.gray5016),
        statePressedStrong: SwiftUI.Color(light: PrimitiveToken.Color.blue90080, dark: PrimitiveToken.Color.gray5040),
        stateSelectedMedium: SwiftUI.Color(light: PrimitiveToken.Color.blue90012, dark: PrimitiveToken.Color.gray5012),
        stateSelectedStrong: SwiftUI.Color(light: PrimitiveToken.Color.blue90080, dark: PrimitiveToken.Color.gray5040)
    )
}
